import { nodes } from '.'

export const networks = [
  {
    name: 'Ethereum',
    chainIdNumber: ['1', '3', '4', '5'],
    chainId: '0x1',
    chainName: 'Ethereum Mainnet',
    symbol: 'eth',
    url: '/ethlogo.png',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'eth',
      decimals: 18,
    },
    rpcUrls: ['https://mainnet.infura.io/v3/undefined'],
    blockExplorerUrls: ['https://etherscan.io'],
  },
  {
    name: 'BSC',
    chainIdNumber: ['56'],
    chainId: '0x38',
    chainName: 'Binance Smart Chain Mainnet',
    symbol: 'bnb',
    url: '/bnblogo.png',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'bnb',
      decimals: 18,
    },
    rpcUrls: nodes,
    blockExplorerUrls: ['https://bscscan.com/'],
  },
  {
    name: 'xDai',
    chainIdNumber: ['100'],
    chainId: '0x64',
    chainName: 'xDai Chain',
    symbol: 'dai',
    url: '/dailogo.png',
    nativeCurrency: {
      name: 'XDAI',
      symbol: 'xdai',
      decimals: 18,
    },
    rpcUrls: ['https://dai.poa.network'],
    blockExplorerUrls: ['https://blockscout.com/xdai/mainnet'],
  },
  {
    name: 'Matic',
    chainIdNumber: ['137'],
    chainId: '0x89',
    chainName: 'Matic Mainnet',
    symbol: 'matic',
    url: '/maticlogo.png',
    nativeCurrency: {
      name: 'MATIC',
      symbol: 'matic',
      decimals: 18,
    },
    rpcUrls: ['https://rpc-mainnet.maticvigil.com'],
    blockExplorerUrls: ['https://explorer.matic.network'],
  },
  {
    name: 'Harmony',
    chainIdNumber: ['1666600000'],
    chainId: '0x63564c40',
    chainName: 'Harmony Mainnet',
    symbol: 'one',
    url: '/harmonylogo.png',
    nativeCurrency: {
      name: 'ONE',
      symbol: 'one',
      decimals: 18,
    },
    rpcUrls: ['https://api.harmony.one'],
    blockExplorerUrls: ['https://explorer.harmony.one/#/'],
  },
  {
    name: 'Avalanche',
    chainIdNumber: ['43114'],
    chainId: '0xa86a',
    chainName: 'Avalanche Mainnet',
    symbol: 'avax',
    url: '/avalanchelogo.png',
    nativeCurrency: {
      name: 'AVAX',
      symbol: 'avax',
      decimals: 18,
    },
    rpcUrls: ['https://api.avax.network/ext/bc/C/rpc'],
    blockExplorerUrls: ['https://cchain.explorer.avax.network/'],
  },
  {
    name: 'HECO',
    chainIdNumber: ['128'],
    chainId: '0x80',
    chainName: 'Huobi Mainnnet',
    symbol: 'ht',
    url: '/huobilogo.png',
    nativeCurrency: {
      name: 'HT',
      symbol: 'ht',
      decimals: 18,
    },
    rpcUrls: ['https://http-mainnet.hecochain.com'],
    blockExplorerUrls: ['https://hecoinfo.com'],
  },
  {
    name: 'Fantom',
    chainIdNumber: ['250'],
    chainId: '0xfa',
    chainName: 'Fantom Mainnet',
    symbol: 'ftm',
    url: '/fantomlogo.png',
    nativeCurrency: {
      name: 'FTM',
      symbol: 'ftm',
      decimals: 18,
    },
    rpcUrls: ['https://rpcapi.fantom.network'],
    blockExplorerUrls: ['https://ftmscan.com'],
  },
]
